In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
import seaborn as sns
sns.set()

In [5]:
from scipy import optimize

In [6]:
from ipywidgets import *

In [7]:
from IPython.display import SVG

In [8]:
from sklearn import datasets

In [9]:
AND = pd.DataFrame({ 'x1':(0,0,1,1) ,
                     'x2':(0,1,0,1),
                     'y':(0,0,0,1)})

In [10]:
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [27]:
w  = np.random.randn(3)*1e-4

In [28]:
w

array([-2.44901825e-05, -5.27784985e-05,  1.18002459e-04])

In [34]:
g = lambda inputs , weights: np.where(np.dot(inputs,weights)>0,1,0)

#If dot product is greater than 0 print 1 otherwise print 0 

In [35]:
inputs = AND[['x1','x2']]
inputs

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [36]:
-np.ones((len(inputs),1))   #Biases   
                            # we can use other numbers also other than -1

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [37]:
a = np.c_[inputs , -np.ones((len(inputs),1))]
a

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [38]:
w

array([-2.44901825e-05, -5.27784985e-05,  1.18002459e-04])

In [39]:
np.dot(a,w)  #Dot product a = 4 x 3
                        # w = 3 x 1
                    # a x w = 4 x 1

array([-0.000118  , -0.00017078, -0.00014249, -0.00019527])

In [40]:
def train(inputs , targets , weights , eta ,n_iterations):
    inputs = np.c_[inputs , -np.ones((len(inputs),1))]
    
    for n in range(n_iterations):
        activations = g(inputs , weights);
        print(n,activations)
        weights = eta*np.dot(np.transpose(inputs),activations - targets)
        print(n,weights)
 
        
    return(weights)

In [41]:
inputs = AND[['x1','x2']]
targets = AND['y']
 
w = train(inputs,targets , w,.3 ,10)     #Learning rate = 10

0 [0 0 0 0]
0 [-0.3 -0.3  0.3]
1 [0 0 0 0]
1 [-0.3 -0.3  0.3]
2 [0 0 0 0]
2 [-0.3 -0.3  0.3]
3 [0 0 0 0]
3 [-0.3 -0.3  0.3]
4 [0 0 0 0]
4 [-0.3 -0.3  0.3]
5 [0 0 0 0]
5 [-0.3 -0.3  0.3]
6 [0 0 0 0]
6 [-0.3 -0.3  0.3]
7 [0 0 0 0]
7 [-0.3 -0.3  0.3]
8 [0 0 0 0]
8 [-0.3 -0.3  0.3]
9 [0 0 0 0]
9 [-0.3 -0.3  0.3]


In [42]:
# print(activation,weights)

In [43]:
w

array([-0.3, -0.3,  0.3])

In [44]:
g(np.c_[inputs , -np.ones((len(inputs),1))],w)  

array([0, 0, 0, 0])

In [45]:
OR  = pd.DataFrame({ 'x1':(0,0,1,1) ,
                     'x2':(0,1,0,1),
                     'y':(0,1,1,1)})
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [46]:
w  = np.random.randn(3)*1e-4
w

array([8.60277377e-05, 1.44156113e-04, 1.01710334e-05])

In [47]:
g = lambda inputs , weights: np.where(np.dot(inputs,weights)>0,1,0)

#If dot product is greater than 0 print 1 otherwise print 0 

In [48]:
inputs = AND[['x1','x2']]
inputs

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [49]:
-np.ones((len(inputs),1))   #Biases   
                            # we can use other numbers also other than -1

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [50]:
a = np.c_[inputs , -np.ones((len(inputs),1))]
a

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [51]:
w

array([8.60277377e-05, 1.44156113e-04, 1.01710334e-05])

In [52]:
np.dot(a,w)  #Dot product a = 4 x 3
                        # w = 3 x 1
                    # a x w = 4 x 1

array([-1.01710334e-05,  1.33985079e-04,  7.58567043e-05,  2.20012817e-04])

In [53]:
def train(inputs , targets , weights , eta ,n_iterations):
    inputs = np.c_[inputs , -np.ones((len(inputs),1))]
    
    for n in range(n_iterations):
        activations = g(inputs , weights);
        print(n,activations)
        weights = eta*np.dot(np.transpose(inputs),activations - targets)
        print(n,weights)
 
        
    return(weights)

In [55]:
inputs = OR[['x1','x2']]
targets = OR['y']
 
w = train(inputs,targets , w,0.001 ,10)     #Learning rate = 20
                                         #iterions = 10

0 [0 0 0 0]
0 [-0.002 -0.002  0.003]
1 [0 0 0 0]
1 [-0.002 -0.002  0.003]
2 [0 0 0 0]
2 [-0.002 -0.002  0.003]
3 [0 0 0 0]
3 [-0.002 -0.002  0.003]
4 [0 0 0 0]
4 [-0.002 -0.002  0.003]
5 [0 0 0 0]
5 [-0.002 -0.002  0.003]
6 [0 0 0 0]
6 [-0.002 -0.002  0.003]
7 [0 0 0 0]
7 [-0.002 -0.002  0.003]
8 [0 0 0 0]
8 [-0.002 -0.002  0.003]
9 [0 0 0 0]
9 [-0.002 -0.002  0.003]


In [56]:
w

array([-0.002, -0.002,  0.003])

In [57]:
g(np.c_[inputs , -np.ones((len(inputs),1))],w)  

array([0, 0, 0, 0])