In [15]:
!pip3 install torch torchvision torchaudio

  Using cached torch-1.12.0-cp39-cp39-win_amd64.whl (161.8 MB)
  Using cached torchvision-0.13.0-cp39-cp39-win_amd64.whl (1.1 MB)


In [1]:
from __future__ import print_function
import torch

In [2]:
torch.__version__

'1.12.0+cpu'

In [3]:
#Randomly defined matrix
a = torch.empty(6,3)
print(a)

tensor([[4.4374e+27, 5.3992e-14, 1.3556e-19],
        [4.5155e+27, 2.1471e+20, 2.8944e+12],
        [7.5338e+28, 1.8037e+28, 1.2102e+25],
        [9.8834e+17, 1.7237e+25, 1.4607e-19],
        [1.2102e+25, 1.6217e-19, 3.0263e+29],
        [1.6488e+22, 7.0976e+22, 1.8515e+28]])


In [6]:
type(a)

torch.Tensor

In [7]:
a = torch.zeros(4,3 , dtype=torch.long)
print(a)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
#Converting list into tensor
a = [7.8,5]
type(a)

list

In [9]:
b = torch.tensor(a)
type(b)

torch.Tensor

In [10]:
#torch always take numerical values
a = torch.tensor(['rumman','ahmad'])

ValueError: too many dimensions 'str'

In [11]:
b = torch.tensor([7.8,5])
b

tensor([7.8000, 5.0000])

In [12]:
#Creating ones

In [13]:
a  = [7.8,5]
type(a)

list

In [14]:
a = torch.tensor(a)
type(a)

torch.Tensor

In [15]:
a = a.new_ones(6,5 , dtype = torch.double) #new methods take in size
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [16]:
a = torch.randn_like(a,dtype = torch.float)   #override dtype
print(a)                                      #Result will be the same size

tensor([[-0.7002, -0.5048,  0.5000, -0.1383,  0.3805],
        [ 1.3597, -0.1160, -0.2910, -1.0316, -0.3043],
        [ 0.1343,  0.5364,  0.0693, -0.3525,  0.7320],
        [-0.8544,  0.7027, -1.3169,  0.5153, -0.3395],
        [ 1.4977,  0.0041, -0.4319, -0.2819, -0.3523],
        [-1.8443, -0.3573,  0.8717, -0.7079, -1.2147]])


In [17]:
print(a.size())

torch.Size([6, 5])


In [18]:
#Operations

In [19]:
b = torch.rand(6,5)
print(b)

tensor([[0.4347, 0.3576, 0.4487, 0.0553, 0.5031],
        [0.0493, 0.4562, 0.2240, 0.0690, 0.3864],
        [0.2871, 0.3696, 0.1597, 0.2034, 0.8867],
        [0.1202, 0.7091, 0.6470, 0.5050, 0.1634],
        [0.4084, 0.2623, 0.3168, 0.4054, 0.2397],
        [0.3061, 0.5603, 0.1859, 0.3111, 0.9265]])


In [20]:
#ADDITION
print(a+b)

tensor([[-0.2655, -0.1472,  0.9487, -0.0831,  0.8836],
        [ 1.4090,  0.3402, -0.0670, -0.9626,  0.0821],
        [ 0.4214,  0.9060,  0.2290, -0.1491,  1.6187],
        [-0.7342,  1.4118, -0.6698,  1.0203, -0.1761],
        [ 1.9062,  0.2664, -0.1151,  0.1236, -0.1126],
        [-1.5382,  0.2030,  1.0576, -0.3967, -0.2882]])


In [21]:
result = torch.empty(6,5)
result

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, -7.2132e-38],
        [ 7.4829e-43, -2.1039e-38,  7.4829e-43, -1.0878e+38,  7.4829e-43],
        [ 1.4013e-45,  0.0000e+00,  7.0065e-45,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [22]:
torch.add(a,b , out = result)   #Providing as an argument
print(result)

tensor([[-0.2655, -0.1472,  0.9487, -0.0831,  0.8836],
        [ 1.4090,  0.3402, -0.0670, -0.9626,  0.0821],
        [ 0.4214,  0.9060,  0.2290, -0.1491,  1.6187],
        [-0.7342,  1.4118, -0.6698,  1.0203, -0.1761],
        [ 1.9062,  0.2664, -0.1151,  0.1236, -0.1126],
        [-1.5382,  0.2030,  1.0576, -0.3967, -0.2882]])


In [23]:
#Adds a to b
b

tensor([[0.4347, 0.3576, 0.4487, 0.0553, 0.5031],
        [0.0493, 0.4562, 0.2240, 0.0690, 0.3864],
        [0.2871, 0.3696, 0.1597, 0.2034, 0.8867],
        [0.1202, 0.7091, 0.6470, 0.5050, 0.1634],
        [0.4084, 0.2623, 0.3168, 0.4054, 0.2397],
        [0.3061, 0.5603, 0.1859, 0.3111, 0.9265]])

In [24]:
a

tensor([[-0.7002, -0.5048,  0.5000, -0.1383,  0.3805],
        [ 1.3597, -0.1160, -0.2910, -1.0316, -0.3043],
        [ 0.1343,  0.5364,  0.0693, -0.3525,  0.7320],
        [-0.8544,  0.7027, -1.3169,  0.5153, -0.3395],
        [ 1.4977,  0.0041, -0.4319, -0.2819, -0.3523],
        [-1.8443, -0.3573,  0.8717, -0.7079, -1.2147]])

In [25]:
b.add_(a)
b

tensor([[-0.2655, -0.1472,  0.9487, -0.0831,  0.8836],
        [ 1.4090,  0.3402, -0.0670, -0.9626,  0.0821],
        [ 0.4214,  0.9060,  0.2290, -0.1491,  1.6187],
        [-0.7342,  1.4118, -0.6698,  1.0203, -0.1761],
        [ 1.9062,  0.2664, -0.1151,  0.1236, -0.1126],
        [-1.5382,  0.2030,  1.0576, -0.3967, -0.2882]])

In [26]:
#Index
a

tensor([[-0.7002, -0.5048,  0.5000, -0.1383,  0.3805],
        [ 1.3597, -0.1160, -0.2910, -1.0316, -0.3043],
        [ 0.1343,  0.5364,  0.0693, -0.3525,  0.7320],
        [-0.8544,  0.7027, -1.3169,  0.5153, -0.3395],
        [ 1.4977,  0.0041, -0.4319, -0.2819, -0.3523],
        [-1.8443, -0.3573,  0.8717, -0.7079, -1.2147]])

In [27]:
a[0]

tensor([-0.7002, -0.5048,  0.5000, -0.1383,  0.3805])

In [28]:
a[0][1]

tensor(-0.5048)

In [30]:
a[:,1]

tensor([-0.5048, -0.1160,  0.5364,  0.7027,  0.0041, -0.3573])

In [31]:
a[:,[2,3]]

tensor([[ 0.5000, -0.1383],
        [-0.2910, -1.0316],
        [ 0.0693, -0.3525],
        [-1.3169,  0.5153],
        [-0.4319, -0.2819],
        [ 0.8717, -0.7079]])

In [32]:
#View (it is used for reshape or resize)

In [33]:
a = torch.randn(3,3)
a

tensor([[-0.6974,  0.1059,  0.3187],
        [ 0.9170,  0.5463,  0.4468],
        [-0.0175, -0.8942, -0.4970]])

In [34]:
a.size()

torch.Size([3, 3])

In [35]:
b = a.view(9)         #coverted to 1row and 9 columns
b                         

tensor([-0.6974,  0.1059,  0.3187,  0.9170,  0.5463,  0.4468, -0.0175, -0.8942,
        -0.4970])

In [36]:
b.size()

torch.Size([9])

In [37]:
c = a.view(-1 , 9)   #the size -1 is inferred from other dimensions
c

tensor([[-0.6974,  0.1059,  0.3187,  0.9170,  0.5463,  0.4468, -0.0175, -0.8942,
         -0.4970]])

In [38]:
c.size()

torch.Size([1, 9])

In [39]:
#Converting a torch tensor to numpy

In [40]:
x = torch.ones(4)
x

tensor([1., 1., 1., 1.])

In [41]:
y = x.numpy()
y

array([1., 1., 1., 1.], dtype=float32)