In [6]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x

In [7]:
print('Tensorflow version : {}'.format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

Tensorflow version : 2.10.0
Keras version: 2.10.0


In [8]:
variable = tf.Variable([3,3])
variable

<tf.Variable 'Variable_1:0' shape=(2,) dtype=int32>

In [9]:
type(variable)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [10]:
#GPU and CPU check
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')

CPU


In [11]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor 'Const:0' shape=() dtype=int32>

In [12]:
#Session used for output
sess = tf.compat.v1.Session()
sess.run(ineuron)

42

In [13]:
#Random
random = tf.random.normal(shape=(2,2) , mean=0 , stddev=1.0)
sess.run(random)

array([[-0.81257546,  0.29933584],
       [-0.52218205, -0.19072217]], dtype=float32)

In [14]:
random_uniform = tf.random.uniform(shape=(2,2) , minval=0 , maxval=10 , dtype=tf.int32)
sess.run(random_uniform)

array([[4, 0],
       [1, 7]])

In [15]:
#variable
var0 = 24
var1 = tf.Variable(42)
var2 = tf.Variable( [  [[0. ,1. ,2.],[3. , 4. , 5.]] , [[6. ,7. ,8.],[9. , 10. ,11.]]   ] )

In [16]:
var0

24

In [17]:
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(var1)

42

In [18]:
sess.run(var2)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)

In [19]:
#Reassign varibles

In [20]:
ineuron = tf.constant(1)
sess.run(ineuron)

1

In [21]:
ineuron  #d-type = int32

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [22]:
ineuron.assign(2) #error because it is constant

AttributeError: 'Tensor' object has no attribute 'assign'

In [23]:
var_reassign = tf.Variable(89.)
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(var_reassign)

89.0

In [24]:
var_reassign  

<tf.Variable 'Variable_4:0' shape=() dtype=float32>

In [25]:
var_reassign = var_reassign.assign(54)
sess.run(var_reassign)

54.0

In [26]:
var_reassign = tf.Variable(98.)
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(var_reassign)

98.0

In [27]:
var_reassign

<tf.Variable 'Variable_5:0' shape=() dtype=float32>

In [28]:
var_reassign = var_reassign.assign(5)
sess.run(var_reassign)

5.0

In [29]:
#Re-Shape

In [30]:
tensor = tf.Variable([ [ [10. , 11. , 12.] , [13. , 14. , 15.] ] , [[16. , 17. , 18.], [19. , 20. , 21.] ] ])
tensor.shape

TensorShape([2, 2, 3])

In [31]:
sess.run(tensor)

FailedPreconditionError: Graph execution error:

Detected at node 'Variable_6/Read/ReadVariableOp' defined at (most recent call last):
    File "C:\Users\rumma\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\rumma\anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "C:\Users\rumma\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
      self.io_loop.start()
    File "C:\Users\rumma\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\rumma\anaconda3\lib\asyncio\base_events.py", line 596, in run_forever
      self._run_once()
    File "C:\Users\rumma\anaconda3\lib\asyncio\base_events.py", line 1890, in _run_once
      handle._run()
    File "C:\Users\rumma\anaconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
      await self.process_one()
    File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
      await dispatch(*args)
    File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
      await result
    File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
      reply_content = await reply_content
    File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 353, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
      result = self._run_cell(
    File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
      return runner(coro)
    File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\rumma\AppData\Local\Temp/ipykernel_21288/2203414573.py", line 1, in <module>
      tensor = tf.Variable([ [ [10. , 11. , 12.] , [13. , 14. , 15.] ] , [[16. , 17. , 18.], [19. , 20. , 21.] ] ])
Node: 'Variable_6/Read/ReadVariableOp'
Could not find variable Variable_6. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/Variable_6/class tensorflow::Var does not exist.
	 [[{{node Variable_6/Read/ReadVariableOp}}]]

Original stack trace for 'Variable_6/Read/ReadVariableOp':
  File "C:\Users\rumma\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rumma\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\rumma\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
    self.io_loop.start()
  File "C:\Users\rumma\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\rumma\anaconda3\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\rumma\anaconda3\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\rumma\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
    await self.process_one()
  File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
    await dispatch(*args)
  File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
  File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
  File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 353, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\rumma\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
    result = self._run_cell(
  File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
    return runner(coro)
  File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\rumma\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\rumma\AppData\Local\Temp/ipykernel_21288/2203414573.py", line 1, in <module>
    tensor = tf.Variable([ [ [10. , 11. , 12.] , [13. , 14. , 15.] ] , [[16. , 17. , 18.], [19. , 20. , 21.] ] ])
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 266, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 247, in _variable_v2_call
    return previous_getter(
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 240, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2755, in default_variable_creator_v2
    return resource_variable_ops.ResourceVariable(
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 268, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1659, in __init__
    self._init_from_args(
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1868, in _init_from_args
    value = gen_resource_variable_ops.read_variable_op(handle, dtype)
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 538, in read_variable_op
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3800, in _create_op_internal
    ret = Operation(


In [32]:
tensor1 = tf.reshape(tensor,[2,6])
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(tensor1)

array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)

In [33]:
tensor2 = tf.reshape(tensor,[1,12])
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(tensor2)

array([[10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]],
      dtype=float32)

In [34]:
#Rank of a Tensor
#It is defined as the number of dimensions , which is the number of indices that are required to specify any particular element 
#of that tensor

In [35]:
rank = tf.rank(tensor)
sess.run(rank)

3

In [36]:
#Specifying an element of a tensor

In [37]:
sess.run(tensor)

array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)

In [38]:
tensor3 = tensor[1,0,2]   #slice = 1 , row = 0 , column = 2
sess.run(tensor3)

18.0

In [39]:
#Math

In [40]:
a = tf.random.normal(shape=(2,2))
print(sess.run(a))

[[-0.18661009  0.14889064]
 [-0.54171     0.04326439]]


In [41]:
b = tf.random.normal(shape=(2,2))
print(sess.run(b))

[[ 0.6016593  -0.39605907]
 [-2.0025687   1.4136943 ]]


In [42]:
c = a+b
print(sess.run(c))

[[ 1.9757371   2.1212337 ]
 [-0.22160935 -0.22046328]]


In [43]:
d = tf.square(c)
print(sess.run(d))

[[0.02500327 3.2245815 ]
 [0.57998335 5.725684  ]]


In [44]:
e = tf.exp(c)
sess.run(c)

array([[ 0.14268467,  1.2929137 ],
       [ 2.2578573 , -1.168915  ]], dtype=float32)

In [45]:
#performing element wise primitive tensor operations

In [46]:
sess.run(tensor)

array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)

In [47]:
sess.run(tensor*tensor)

array([[[100., 121., 144.],
        [169., 196., 225.]],

       [[256., 289., 324.],
        [361., 400., 441.]]], dtype=float32)

In [48]:
#Broadcasting

In [49]:
sess.run(tensor)

array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)

In [50]:
tensor4 = tensor*4
sess.run(tensor4)

array([[[40., 44., 48.],
        [52., 56., 60.]],

       [[64., 68., 72.],
        [76., 80., 84.]]], dtype=float32)

In [51]:
#Transpose Matrix multiplication

In [54]:
matrix_u = tf.constant([[6 , 7 , 6]])
matrix_v = tf.constant([[3 , 4 , 3]])
result = tf.matmul(matrix_u , tf.transpose(a=matrix_v))
sess.run(result)

array([[64]])

In [55]:
matrix_u.shape

TensorShape([1, 3])

In [56]:
matrix_v.shape

TensorShape([1, 3])

In [57]:
tf.transpose(a=matrix_v).shape

TensorShape([3, 1])

In [58]:
#Casting  a tensor to another datatype

In [59]:
sess.run(tensor)

array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)

In [60]:
 tensor.dtype   #d-type = float32

tf.float32

In [61]:
i = tf.cast(tensor , dtype= tf.int32)
sess.run(i)

array([[[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21]]])

In [62]:
i.dtype

tf.int32

In [63]:
#casting with truncation

In [64]:
num = tf.constant(4.9)
sess.run(num)

4.9

In [65]:
num.dtype

tf.float32

In [66]:
j = tf.cast(num,dtype=tf.int32)
sess.run(j)

4

In [67]:
j.dtype

tf.int32

In [68]:
#Ragged tensors

In [69]:
tf.constant([   [9,7,4,3],[],[11,12,8],[3],[7,8]  ]) #error

C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py:455: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  nparray = np.array(values, dtype=np_dt)


ValueError: Expected values [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]] to be a dense tensor with shape [5, 4], but got shape [5].

In [70]:
ragged = tf.ragged.constant([  [9,7,4,3],[],[11,12,8],[3],[7,8]     ])
sess.run(ragged)

tf.RaggedTensorValue(values=array([ 9,  7,  4,  3, 11, 12,  8,  3,  7,  8]), row_splits=array([ 0,  4,  4,  7,  8, 10], dtype=int64))

In [71]:
sess.run(ragged[0,:])

array([9, 7, 4, 3])

In [65]:
sess.run(ragged[1,:])

array([], dtype=int32)

In [66]:
sess.run(ragged[2,:])

array([11, 12,  8])

In [67]:
sess.run(ragged[3,:])

array([3])

In [68]:
sess.run(ragged[4,:])

array([7, 8])

In [69]:
#Squared difference of tensors

In [70]:
varx = [4,5,6,1,2]
vary = 8 

In [71]:
varz = tf.math.squared_difference(varx,vary)   # (varx-vary)*(varx-vary)
sess.run(varz)  

array([16,  9,  4, 49, 36])

In [72]:
#Mean
numbers = tf.constant([  [8.,9.],[1.,2.]  ])
sess.run(numbers)

array([[8., 9.],
       [1., 2.]], dtype=float32)

In [73]:
#1- Across all axes
mean_all = tf.reduce_mean(input_tensor = numbers)
sess.run(mean_all)

5.0

In [74]:
#2- Across columns
mean_column = tf.reduce_mean(input_tensor = numbers , axis=0)
sess.run(mean_column)

array([4.5, 5.5], dtype=float32)

In [75]:
#3- Across rows
mean_rows = tf.reduce_mean(input_tensor = numbers , axis=1)
sess.run(mean_rows)

array([8.5, 1.5], dtype=float32)

In [76]:
#4- Getting real Dimension
mean_rows_dim = tf.reduce_mean(input_tensor = numbers , axis=1 , keepdims=True)
sess.run(mean_rows_dim)

array([[8.5],
       [1.5]], dtype=float32)

In [77]:
mean_columns_dim = tf.reduce_mean(input_tensor = numbers , axis=0 , keepdims=True)
sess.run(mean_columns_dim)

array([[4.5, 5.5]], dtype=float32)

In [78]:
#Random defines values generation
random_num = tf.random.normal(shape = (3,2), mean = 10. , stddev = 2.0 )
sess.run(random_num)

array([[ 9.981023,  7.266905],
       [10.717081, 11.670806],
       [12.945927, 13.068205]], dtype=float32)

In [79]:
#Seed
# tf.random.set_seed(11)
random_num = tf.random.normal(shape = (3,2), mean = 10. , stddev = 2.0  , seed=11)
sess.run(random_num)

array([[12.807886,  6.620744],
       [ 9.577319, 12.300316],
       [13.024887, 10.856893]], dtype=float32)

In [80]:
#Random uniform values

In [81]:
uniform = tf.random.uniform(shape=(2,4) , minval=0 , maxval=None , dtype = tf.float32 , seed = None , name = None )
sess.run(uniform)

array([[0.90556324, 0.5207877 , 0.3062545 , 0.86990476],
       [0.7170148 , 0.49558783, 0.44457328, 0.32603085]], dtype=float32)

In [82]:
random_num1 = tf.random.uniform(shape = (2,2) , maxval = 10 , dtype = tf.int32)
sess.run(random_num1)

array([[3, 7],
       [3, 2]])

In [83]:
random_num2 = tf.random.uniform(shape = (2,2) , maxval = 10 , dtype = tf.int32)
sess.run(random_num2)

array([[1, 3],
       [0, 5]])

In [84]:
#setting the seed

In [85]:
random_num1 = tf.random.uniform(shape = (2,2) , maxval = 10 , dtype = tf.int32 , seed = 11)
sess.run(random_num1)

array([[1, 2],
       [9, 9]])

In [86]:
random_num2 = tf.random.uniform(shape = (2,2) , maxval = 10 , dtype = tf.int32 , seed = 10)
sess.run(random_num2)

array([[0, 2],
       [5, 7]])

In [87]:
#Add  Two matrix

In [88]:
dice11 = tf.Variable(tf.random.uniform([10,1] , minval=1 , maxval=7 , dtype=tf.int32))
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(dice11)

array([[5],
       [5],
       [5],
       [4],
       [2],
       [1],
       [3],
       [1],
       [6],
       [5]])

In [89]:
dice12 = tf.Variable(tf.random.uniform([10,1] , minval=1 , maxval=7 , dtype=tf.int32))
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(dice12)

array([[6],
       [5],
       [5],
       [1],
       [4],
       [4],
       [2],
       [6],
       [3],
       [3]])

In [90]:
dice_sum = dice11 + dice12
sess.run(dice_sum)

array([[ 9],
       [ 8],
       [11],
       [ 4],
       [ 8],
       [ 7],
       [ 6],
       [11],
       [ 4],
       [ 4]])

In [91]:
final_matrix = tf.concat(values = [dice11 , dice12 , dice_sum] , axis = 1)
sess.run(final_matrix)

array([[ 3,  6,  9],
       [ 3,  5,  8],
       [ 6,  5, 11],
       [ 3,  1,  4],
       [ 4,  4,  8],
       [ 3,  4,  7],
       [ 4,  2,  6],
       [ 5,  6, 11],
       [ 1,  3,  4],
       [ 1,  3,  4]])

In [92]:
#Argmax 
tensor_id = tf.constant([12 , 11 , 51 , 42 , 6 , 16 , -8 , -19 , 31])
sess.run(tensor_id)

array([ 12,  11,  51,  42,   6,  16,  -8, -19,  31])

In [93]:
index  = tf.argmax(input = tensor_id)
sess.run(index)

2

In [94]:
#Argmin
tensor_id = tf.constant([12 , 11 , 51 , 42 , 6 , 16 , -8 , -19 , 31])
sess.run(tensor_id)

array([ 12,  11,  51,  42,   6,  16,  -8, -19,  31])

In [95]:
index  = tf.argmin(input = tensor_id)
sess.run(index)

7

In [96]:
#Saving and Restoring using a checkpoint

In [97]:
variable1 = tf.Variable([ [5,6,9,3],[14,15,16,18] ])
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(variable1)

array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])

In [98]:
checkpoint = tf.train.Checkpoint(var=variable1) #saved the data
savepath = checkpoint.save('./vars')

FailedPreconditionError: Could not find variable Variable_8. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/Variable_8/class tensorflow::Var does not exist.
	 [[node Variable_8/Read/ReadVariableOp (defined at \AppData\Local\Temp/ipykernel_30548/1946014817.py:1) ]]

Original stack trace for 'Variable_8/Read/ReadVariableOp':
  File "\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
    self.io_loop.start()
  File "\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "\anaconda3\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "\anaconda3\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
    await self.process_one()
  File "\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
    await dispatch(*args)
  File "\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
  File "\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
  File "\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 353, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
    result = self._run_cell(
  File "\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
    return runner(coro)
  File "\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "\AppData\Local\Temp/ipykernel_30548/1946014817.py", line 1, in <module>
    variable1 = tf.Variable([ [5,6,9,3],[14,15,16,18] ])
  File "\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 262, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 244, in _variable_v2_call
    return previous_getter(
  File "\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 237, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "\anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2662, in default_variable_creator_v2
    return resource_variable_ops.ResourceVariable(
  File "\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1584, in __init__
    self._init_from_args(
  File "\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1777, in _init_from_args
    value = gen_resource_variable_ops.read_variable_op(handle, dtype)
  File "\anaconda3\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 483, in read_variable_op
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)


In [99]:
sess.run( variable1.assign( [ [0,0,0,0],[0,0,0,0] ]))

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [100]:
checkpoint.restore(savepath)
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(variable1)

NameError: name 'savepath' is not defined

In [101]:
#Functions

In [102]:
def f1(x,y):
    return tf.reduce_mean(input_tensor = tf.multiply(x**3,6)+y**3)

In [103]:
f1(4,5)

<tf.Tensor 'Mean_5:0' shape=() dtype=int32>

In [104]:
sess.run(f1(4,5))

509

In [105]:
#Gradient Tape     #dy/dx

In [11]:
a = tf.random.normal(shape=(2,2))
sess.run(a)

array([[ 2.2168741 ,  0.605255  ],
       [-1.3201123 , -0.17680708]], dtype=float32)

In [12]:
b = tf.random.normal(shape=(2,2))
sess.run(b)

array([[ 0.94417965, -1.5929502 ],
       [-0.42111087,  1.5636042 ]], dtype=float32)

In [13]:
#With watch  (it will always change)
with tf.GradientTape() as tape:
    tape.watch(a)           #It will keep watch  all variables of a
    c = tf.sqrt(tf.sqrt(a) + tf.square(b))
    dc_da = tape.gradient(c,a)
    sess.run(dc_da)

In [14]:
sess.run(c)

array([[      nan, 0.7669096],
       [      nan, 1.0921642]], dtype=float32)

In [146]:
sess.run(dc_da)

array([[       nan, 0.18681024],
       [       nan,        nan]], dtype=float32)

In [156]:
#Without watch (remains same)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.sqrt(a) + tf.square(b))
    dc_da = tape.gradient(c,a)

In [157]:
sess.run(c)

array([[       nan, 0.9701002 ],
       [       nan, 0.62336737]], dtype=float32)

In [158]:
sess.run(dc_da)

TypeError: Fetch argument None has invalid type <class 'NoneType'>

In [ ]:
#Sequential Model

In [159]:
#Loding dataset

In [166]:
mnist_data = tf.keras.datasets.mnist
mnist_data.load_data()

11493376/11490434 [==============================] - 2s 0us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [169]:
#defining training and testing data
(train_x,train_y) , (test_x,test_y) = mnist_data.load_data()

In [171]:
train_x

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [172]:
train_y

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [173]:
test_x

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [174]:
test_y

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [175]:
#defining variables

In [176]:
epochs = 10
batch_size = 32

In [181]:
#normalize all the dta points and cast the labels to int64
train_x,test_x = tf.cast(train_x/255.0 , tf.float32) , tf.cast(test_x/255.0 , tf.float32)
train_y,test_y = tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

In [182]:
sess.run(train_x)

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [183]:
sess.run(test_x)

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [184]:
sess.run(train_y)

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [185]:
sess.run(test_y)

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [188]:
#Building a model
mnistmodel1 = tf.keras.models.Sequential([
    
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512 , activation=tf.nn.tanh),
    tf.keras.layers.Dense(60 , activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(34 , activation=tf.nn.relu),
    tf.keras.layers.Dense(56 , activation=tf.nn.relu),
    tf.keras.layers.Dense(23 , activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10 , activation=tf.nn.softmax)


])

In [191]:
#Compiling the model
optimiser = tf.keras.optimizers.Adam()
mnistmodel1.compile(optimizer = optimiser , loss='sparse_categorical_crossentropy' , metrics= ['accuracy'])

In [197]:
#Fitting the model
mnistmodel1.fit(train_x,train_y , batch_size = 32 , epochs=5,steps_per_epoch=5)

Train on 5 samples
Epoch 1/5
5/5 [==============================] - 5s 969ms/step - batch: 2.0000 - size: 1.0000 - loss: 0.1843 - accuracy: 0.9487
Epoch 2/5
5/5 [==============================] - 5s 903ms/step - batch: 2.0000 - size: 1.0000 - loss: 0.1822 - accuracy: 0.9491
Epoch 3/5
5/5 [==============================] - 4s 893ms/step - batch: 2.0000 - size: 1.0000 - loss: 0.1820 - accuracy: 0.9491
Epoch 4/5
5/5 [==============================] - 5s 934ms/step - batch: 2.0000 - size: 1.0000 - loss: 0.1793 - accuracy: 0.9500
Epoch 5/5
5/5 [==============================] - 5s 972ms/step - batch: 2.0000 - size: 1.0000 - loss: 0.1790 - accuracy: 0.9501


In [201]:
#predicting 
mnistmodel1.predict(test_x,steps=5)

array([[3.9999452e-04, 1.5489035e-06, 4.3142281e-06, ..., 7.3494939e-06,
        1.8985918e-05, 3.7784214e-04],
       [9.9987519e-01, 2.4337996e-10, 3.3424675e-07, ..., 1.0529568e-08,
        3.5177575e-10, 1.2041166e-04],
       [1.2330379e-03, 4.6466007e-03, 5.4732244e-03, ..., 3.2944870e-03,
        2.8943457e-04, 4.7368775e-03],
       ...,
       [6.1452811e-05, 5.3842960e-08, 9.0048695e-07, ..., 9.3703454e-09,
        3.1178133e-05, 1.8868575e-05],
       [1.0292734e-05, 1.0930051e-05, 1.9414260e-04, ..., 1.1218219e-08,
        2.0580883e-05, 1.8813688e-07],
       [4.4140157e-05, 4.1570095e-04, 4.2029358e-03, ..., 6.7379238e-05,
        9.8556399e-01, 1.8642714e-03]], dtype=float32)

In [214]:
#Predicting model outcomes
import numpy as np
predict_x=mnistmodel1.predict(test_x,steps=5) 
classes_x=np.argmax(predict_x,axis=1)
classes_x

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [199]:
#score
mnistmodel1.evaluate(test_x,test_y,steps=5)    #will produce train 100% accuracy  and then test accuracy 97%

C:\Users\rumma\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:2426: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '


[0.1055445447564125, 0.9698333]

In [216]:
#saving the model
tf.saved_model.save(mnistmodel1 , export_dir = 'C:/Users/rumma/Tensorflow' )


FOR DEVS: If you are overwriting _tracking_metadata in your class, this property has been used to save metadata in the SavedModel. The metadta field will be deprecated soon, so please move the metadata to a different file.



FOR DEVS: If you are overwriting _tracking_metadata in your class, this property has been used to save metadata in the SavedModel. The metadta field will be deprecated soon, so please move the metadata to a different file.


INFO:tensorflow:Assets written to: C:/Users/rumma/Tensorflow\assets


INFO:tensorflow:Assets written to: C:/Users/rumma/Tensorflow\assets


In [215]:
#Keras function API 
#definition

In [ ]:
#same