# !pip install tensorflow==2.5.0

In [1]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x

In [2]:
import tensorflow as tf

hello_constant = tf.constant('Hello world!')
hello_constant

<tf.Tensor 'Const:0' shape=() dtype=string>

In [3]:
import tensorflow as tf

#Declaring our own constant
hello_constant = tf.constant('Hello world!')

#Session used for output
sess = tf.compat.v1.Session()
print(sess.run(hello_constant))

b'Hello world!'


In [4]:
#Creating variables
A = tf.constant(1234)
A

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [5]:
print(sess.run(A))

1234


In [6]:
#1-D array
B = tf.constant([123,456,789])
B

<tf.Tensor 'Const_3:0' shape=(3,) dtype=int32>

In [7]:
print(sess.run(B))

[123 456 789]


In [8]:
#3-D array 
C = tf.constant([[123,456,789] , [222,333,444]])
C

<tf.Tensor 'Const_4:0' shape=(2, 3) dtype=int32>

In [9]:
print(sess.run(C))

[[123 456 789]
 [222 333 444]]


In [10]:
#Placeholder 
#it is variable in which you pass a data into a runtime

In [11]:
#For string 
x = tf.compat.v1.placeholder(tf.string)
print(sess.run(x,feed_dict={x:'hello world'}))

hello world


In [12]:
#Examples for other datasets
x = tf.compat.v1.placeholder(tf.string)
y = tf.compat.v1.placeholder(tf.int32)
z = tf.compat.v1.placeholder(tf.float32)

print(sess.run(x,feed_dict={x:'hello world',y:123 , z:45.67}))
print(sess.run(y,feed_dict={x:'hello world',y:123 , z:45.67}))
print(sess.run(z,feed_dict={x:'hello world',y:123 , z:45.67}))

hello world
123
45.67


In [13]:
#Tensflow math

In [14]:
#Add
x = tf.add(2, 5)
print(sess.run(x))

7


In [15]:
#subtract
y = tf.subtract(5, 3)
print(sess.run(y))

2


In [16]:
#multiply
z = tf.multiply(2, 5)
print(sess.run(z))

10


In [17]:
# Add
a = tf.divide(4, 2)
print(sess.run(a))

2.0


In [19]:
#For math operation You need same datatype

tf.subtract(3,2.0)  #error

TypeError: Expected int32 passed to parameter 'y' of op 'Sub', got 2.0 of type 'float' instead. Error: Expected int32, but got 2.0 of type 'float'.

In [20]:
#Converting float into integer
sub = tf.subtract(tf.cast(tf.constant(2.0),tf.int32) ,tf.constant(3))
print(sess.run(sub))

-1


In [21]:
#variables
x = tf.Variable(5)

In [22]:
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(x)

5

In [23]:
#Truncated Normal()

In [24]:
n_features =120
n_labels = 5 
weights = tf.Variable(tf.random.truncated_normal((n_features,n_labels)))
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(weights)

array([[ 1.50165665e+00,  9.52928722e-01, -2.04054177e-01,
        -3.61706078e-01, -1.25395989e+00],
       [-1.03329909e+00,  8.26774299e-01,  5.57024539e-01,
        -7.74281979e-01, -5.27829587e-01],
       [ 8.33321095e-01,  6.29820228e-01, -3.47650230e-01,
         2.14055344e-01, -1.90529001e+00],
       [-1.04253447e+00,  4.04971898e-01, -6.19019687e-01,
         6.82911038e-01, -3.59560102e-01],
       [ 1.73888516e+00, -2.09446788e-01,  3.95744741e-01,
         1.06841028e-01,  1.72862625e+00],
       [-1.72789609e+00,  1.05402052e+00, -1.68983436e+00,
        -6.23708010e-01, -1.69266117e+00],
       [ 1.62704423e-01, -2.90117860e-01,  1.32642612e-01,
         1.21883178e+00, -3.34348351e-01],
       [-1.10729384e+00, -3.92182469e-01,  4.53391671e-01,
         8.27848554e-01,  9.92718041e-01],
       [ 6.98150873e-01,  6.86966717e-01, -6.40855283e-02,
        -7.98759282e-01, -1.09944415e+00],
       [ 6.00316763e-01,  1.18476497e-02, -1.15730798e+00,
         1.28848374e-01

In [25]:
o = tf.random.truncated_normal((n_features,n_labels))
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(o)

array([[-3.17062885e-01, -6.52248502e-01, -1.02450192e+00,
         8.71730596e-02, -1.21767581e+00],
       [-5.98498359e-02,  7.18035698e-01, -8.69864106e-01,
        -1.71251392e+00, -1.34094894e+00],
       [ 8.36057305e-01, -5.32766581e-01,  1.19598126e+00,
         1.52399063e-01, -4.86026764e-01],
       [ 7.49812186e-01, -2.83998847e-01, -7.56612420e-01,
        -4.74340767e-01,  1.13199323e-01],
       [ 6.01136267e-01, -7.28944659e-01,  1.85344958e+00,
         1.67372918e+00, -1.09143329e+00],
       [-1.26137793e+00,  1.40585616e-01, -1.71343315e+00,
        -4.23449688e-02, -3.37001771e-01],
       [-4.80066650e-02, -1.94610596e-01,  1.85990763e+00,
        -5.42339742e-01, -1.82050395e+00],
       [-5.82739115e-01,  1.53108108e+00,  6.18147135e-01,
        -8.72486472e-01, -7.22276345e-02],
       [-6.79080725e-01, -1.21890521e+00, -7.79037297e-01,
        -2.69807130e-01,  1.70267189e+00],
       [ 8.45141292e-01, -4.02606316e-02,  1.18715453e+00,
         8.54642212e-01

In [26]:
#Zeros

In [27]:
import numpy as np
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))

init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(bias)

array([0., 0., 0., 0., 0.], dtype=float32)

In [29]:
#Softmax

In [30]:
x = tf.nn.softmax([1.2,0.9,0.4])
sess.run(x)

array([0.45659032, 0.3382504 , 0.20515925], dtype=float32)

In [31]:
#One hot encoding

In [32]:
#Reduce sum
x = tf.reduce_sum([1,2,3,4,5])
sess.run(x)  #gives the sum

15

In [33]:
#Natural log
x = tf.math.log(100.0)
sess.run(x)

4.6051702

In [34]:
#cross entropy 
import tensorflow as tf

softmax_data = [0.7,0.2,0.1]
one_hot_data = [1.0,0.0,0.0]

softmax = tf.compat.v1.placeholder(tf.float32)
one_hot = tf.compat.v1.placeholder(tf.float32)

#Print cross Entropy
cross_entrpy = -tf.reduce_sum(tf.multiply(one_hot_data,tf.math.log(softmax_data)))
sess.run(cross_entrpy)

0.35667497